language: node_js
env: TRAVIS_CI=true
before_script:
  - npm install -g gulp
script: gulp build
before_deploy: git config --global user.email publish@travis.github && git config --global user.name "Travis"
deploy:
  - edge: true
    skip_cleanup: true
    provider: script
    script: gulp deploy
    on:
      branch: master