language:
- node_js
node_js:
- 5.0.0
before_script:
- npm install -g gulp
script:
- gulp build
before_deploy:
- git config --global user.email publish@travis.github
- git config --global user.name "Travis (DevChampions)"
deploy:
  provider: script
  skip_cleanup: true
  script: gulp deploy
  on:
    branch: master
notifications:
  slack:
    secure: yB4Tcyg0wpv739xwZktCru4G+sZdq2gv8zz/GdBB6WS2Ggbak+pEOHM6U2BXHQRsGu0uhkf2/2uckAYsrGX1P4jaiZepKwrx5J25tFZbNiYV1jWnTO6fgp44IEN1vNud+PhnrmPTDAoFCbDviGYvKNXbSM2exUAW3SpdDw9rBDwrHgdeYa/Xvz8wNjCYyrl0IowaSJgDSxwoHZWxpqo6ugBS22PngDarRLkw7EwwE8RVTmh9/Tkm0XysXw94Bx+Ld0Qv4jv140x9ArCwEylzcp2398iOwFYrPcehu/HeTQ4V2Eqh48APc+IMiHR8Y6k8VO5oM38QYB/tCwnsaTtWyQC06EqV61yDJet7pczfA2i0uWVz0iUwvXodaZ3nWMGKYG6jOOqGp29HJt76gVXsutkgMe8+ZX8HhtV4nobNasLAvKFRyjCI4u81O+ZCDNB97DThjt5cmt4TJZSvTU2l5TXXl6WWdNtiFK76Vm8q4lud0X6MobDmBanExuE5qsyyfevZybezX9Q4AW+JtG8Tr/7pWCxyFhp77RtgFW8iR/uHcn95REsFBT6ntFxY713I93frwqkXYrd4UGa/1MkpGYF4Xr6Jbk01XoPRC85DutO4D2tPP6aYX3Jr5JNOVPpgT+YOwhouEDMavQkLuxotMgSG2lbtJT3OVJo9t+THAEc=
